#!/bin/bash

# これはhttpで叩かれる
# local実行ではない

cd `dirname $0`
set -e

COMMENT=${2:-Update score}
EASY=${1:-full}

source gplus/bin/activate

python update.py $EASY $@

eval `ssh-agent`
ls ~/golf/webpage/gplus/www/id_rsa_github
ssh-add ~/golf/webpage/gplus/www/id_rsa_github

git add docs
git commit -m "$COMMENT" && git push
