#!/bin/bash


cd `dirname $0`
set -e

COMMENT=${1:-Update score}

# requirements: python3.11
# source gplus/bin/activate

python update.py

ssh-add ~/golf/webpage/gplus/www/id_rsa_github

git add docs
git commit -m "$COMMENT" && git push
